sudo: required

branches:
  only:
    - master

services:
  - docker

before_install:
  - docker build -t vafrcor/complex-client-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true vafrcor/complex-client-test npm run test -- --coverage

after_success:
  - docker build -t vafrcor/complex-client ./client
  - docker build -t vafrcor/complex-nginx ./nginx
  - docker build -t vafrcor/complex-server ./server
  - docker build -t vafrcor/complex-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vafrcor/complex-client
  - docker push vafrcor/complex-nginx
  - docker push vafrcor/complex-server
  - docker push vafrcor/complex-worker

deploy:
  edge: true
  on: 
    branch: master
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-130518357428"
  bucket_path: "multi-docker-deployer"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
