apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate 
metadata:
  name: tsts-site-tls
spec:
  secretName: tsts-site
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    commonName: tsts.tsts
    dnsNames:
      - tsts.site
      - www.tsts.site 
    acme:
      config:
        - http01:
            ingressClass: nginx
          domains:
            - tsts.site
            - www.tsts.site
